### ISSUE TITLE
"appears to be corrupt"

### ISSUE THREAD

**Issue by titaniumbones** [honsiorovskyi/open-url-in-container#1]
Hi,

Building on arch linux w/ node 10.16 (LTS/Dubnium). `yarn build` succeeds with some smal lwarnings: 

```
yarn build
yarn run v1.17.3
warning ../package.json: No license field
$ web-ext build --overwrite-dest --source-dir ./src
Applying config file: ./package.json
Building web extension from /home/matt/src/open-url-in-container/src
Your web extension is ready: /home/matt/src/open-url-in-container/web-ext-artifacts/open_external_links_in_a_container-1.0.2.zip
Done in 0.57s.
```

but Firefox nightly reports "This add-on could not be installed because it appears to be corrupt".

I did have some warnings on instlaling packages: 

```
yarn
yarn install v1.17.3
warning ../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 16.29s.
```
but that just seems to be a well-known issue with fsevents. 

Happy to help with debugging! Thanks for this cool project.

**Comment by honsiorovskyi** [comment]
Hey @titaniumbones, thank you for creating an issue!

I don't think `fsevents` is the reason for the Firefox error. What I suspect is that it fails because of absence of signature and extension ID in the extension. But the extension works if you try to "temporary load" the directory in the debug mode, and also this .zip file generated by web-ext was approved by Mozilla for their addons store, and it can be installed successfully.

Cheers!

**Comment by titaniumbones** [comment]
which .zip file? and thank you!

**Comment by honsiorovskyi** [comment]
A .zip file that web-ext generates as a result of the build process, i.e. the bundled extension itself. That's the file I submitted for Addons Store, and once it got signed by Mozilla, it can be installed now from here: https://addons.mozilla.org/en-US/firefox/addon/open-url-in-container/.

**Comment by honsiorovskyi** [comment]
Closing this as stale. Please consider reopening it if you still have problems.

**Comment by titaniumbones** [comment]
Thanks and sorry for leaving this hanging! I will try again when I have time and report back if there's a new issue.

**Comment by honsiorovskyi** [comment]
@titaniumbones no problem! I just want to avoid the issue tracker to be cluttered. Thanks for understanding, and feel free to come back in touch if you have any issues.
