### ISSUE TITLE
Favicon doesn't work

### ISSUE THREAD

**Issue by Galliver7** [honsiorovskyi/open-url-in-container#16]
I've migrate bookmarks to the custom protocol handler, then Favicon doesn't work. I think since implementation, Firefox doesn't parse Favicon wherein custom protocol handler.
Could we fix this issue like adding parse and set favicon feature by open-url-in-container?

**Comment by honsiorovskyi** [comment]
Hey @Galliver7, thank for the report. I don't know if it's technically possible, but I will look into it.

**Comment by MichaelTunnell** [comment]
I dont think it is possible to have the favicon work because Firefox automatically pulls those when loading the bookmark. . . but I am ok with that. This extension is too awesome to be a deal breaker. :sunglasses:

**Comment by rafaelgssa** [comment]
Yeah, I also don't think it's possible to do anything about this on the extension side, but, as posted [here](https://github.com/mozilla/multi-account-containers/issues/323#issuecomment-535956329), you can add them manually if you don't mind working with userChrome.css.

**Comment by honsiorovskyi** [comment]
Hi @Galliver7!

I just pushed a new preview version to master, where I managed to implement favicon rendering in bookmarks (if you don't mind veeeery long URLs there :smiley:).

All you have to do is to create a bookmark using the new popup menu, and then click the bookmark once. After the first loading, it should display a proper favicon.

If you're interested, [here](https://github.com/honsiorovskyi/open-url-in-container/blob/master/src/js/popup/bookmark.js#L13-L17) and [here](https://github.com/honsiorovskyi/open-url-in-container/blob/master/src/js/opener/opener.js#L18-L31) are some implementation details.

Please bear in mind that this build is still experimental and not yet available through AMO, but you can have a look at it [in the releases section](https://github.com/honsiorovskyi/open-url-in-container/releases/tag/2.0.0alpha5) on Github.

I'm closing this issue now, please feel free to reopen it if needed.
