### ISSUE TITLE
Incorrect interpreter on Ubuntu

### ISSUE THREAD

**Issue by bperraudin** [honsiorovskyi/open-url-in-container#19]
Executing the launcher on Ubuntu returns the following error:

```
/path/to/firefox-container: 50: /path/to/firefox-container: Syntax error: Bad for loop variable
```

On Ubuntu, `sh` points to `dash` which doesn't support C-style for loops.

**Comment by bperraudin** [comment]
Changing the shebang line to `#!/bin/bash` resolves the issue.

**Comment by honsiorovskyi** [comment]
Hey @bperraudin thank you very much for the report, I'll change the interpreter to `/bin/bash`.
