### ISSUE TITLE
Deleting and modifying containers

### ISSUE THREAD

**Issue by tukusejssirs** [honsiorovskyi/open-url-in-container#39]
Thanks for the extension!

It’s just passed my mind: if we can create new containers, can we also delete or modify them? ;)

**Comment by honsiorovskyi** [comment]
Hi @tukusejssirs, thanks for your proposal! I'd like to keep this extension as minimal as possible — only doing what the title says — open URLs in containers.

But I like the idea and maybe at some point I could create another extension for container management from command line.

Or you (or someone else) could do it as well, maybe using the same principle of custom URL handlers and/or even reusing some code from this extension :)

I'll close this issue for now, but please feel free to continue with discussion if you want.

**Comment by hkfsc** [comment]
> Hi @tukusejssirs, thanks for your proposal! I'd like to keep this extension as minimal as possible — only doing what the title says — open URLs in containers.
> 
> But I like the idea and maybe at some point I could create another extension for container management from command line.
> 
> Or you (or someone else) could do it as well, maybe using the same principle of custom URL handlers and/or even reusing some code from this extension :)
> 
> I'll close this issue for now, but please feel free to continue with discussion if you want.

Have you made anything for achieving this? thanks!
