### ISSUE TITLE
Open multiple URLs

### ISSUE THREAD

**Issue by jordan-schneider** [honsiorovskyi/open-url-in-container#90]
Is there a way to specify that multiple URLs should be opened in one command?

**Comment by honsiorovskyi** [comment]
Hi @jordan-schneider! Unfortunately, currently it's not possible. I plan some improvements to the launcher, and maybe it becomes possible in future versions, but I can't promise anything soon.

Alternatively you can use something like:
```
echo URL1 URL2 URL3 | xargs -n1 firefox-container YOUR_OPTIONS
```

**Comment by jordan-schneider** [comment]
Thanks for letting me know. My issue was that firefox didn't always open the tabs in the correct order, or even the window that I intended, but I found a hack within i3-msg to make it work. Thanks for building such a useful tool!

**Comment by honsiorovskyi** [comment]
Thanks for sharing! I'll pay more attention to order and windows management in the future updates.
