### ISSUE TITLE
Persistent "Choose an application to open the ext+container link" prompt in Firefox 88 (Win 10)

### ISSUE THREAD

**Issue by JpTiger** [honsiorovskyi/open-url-in-container#97]
I think this started with the update to Firefox 88, but I now get this little popup every time I try using this extension with a shell script in windows: 
<img width="295" alt="Screenshot 2021-04-28 111001" src="https://user-images.githubusercontent.com/7218432/116427743-4bd41500-a812-11eb-9821-87f6a4d961d4.png">

This doesn't seem like a bad thing, you just click the checkbox to always use the extension to open that kind of link. But for some reason, whether you check the box or not, you get the prompt asking you about this every time. I don't know why the setting isn't sticking. It's possible this is on Firefox's end, but maybe there's a workaround possible here?

**Comment by mupi2k** [comment]
This is absolutely on FireFox's end. Reverting to 87 resolves the issue, at the cost of not having an up-to-date browser.
Also, if you click the link, which is almost invisible in the blue bar, under "Open URL in a container", you can open the link, and this time it will open without prompting you.  This seems to be signalling that FF is now actively preventing the (scripted) opening of external links. ( I have another extension that I rarely use in this way, and tested it, and it has the same problem).

**Comment by JpTiger** [comment]
Sounds convincing to me. I've opened a bug report in bugzilla for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1709141

We'll see what they say...

**Comment by JpTiger** [comment]
Bug I opened w Bugzilla merged with this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1700976

Looks like they're aware of the issue and are working on it. Closing this one here.

**Comment by christophgysin** [comment]
From the upstream bug:
> For an immediate local workaround for you, create the pref network.protocol-handler.prompt-from-external as a boolean in about:config and set it to false.

**Comment by JpTiger** [comment]
Upstream bug is now reported as closed in Firefox 90. Might be a bit before that version trickles down to stable release.

**Comment by mupi2k** [comment]
Thanks for the update.  I've had other priorities, but I was successfully
able to implement the workaround.  A couple of my co-workers reported they
were not able to do it, though I suspect user error :D  Either way, final
resolution is good news

**Comment by hadess** [comment]
I still see this problem with the Firefox Flatpak from Flatub and filed a new bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1891428
