### ISSUE TITLE
Issue with the "Choose an application to open" popup in FireFox on MacOS

### ISSUE THREAD

**Issue by spencersmith** [honsiorovskyi/open-url-in-container#98]
Hi, 

I'm working on some scripting using this extension and am running into an annoying bug. Every time I open a link via the command line I'm getting a popup asking which application I want to use to open the link. (Screenshot below) I've tried the "Always use the app" toggle, and always get the same result. This happens with both the launcher, and by passing in `ext+container:...` to `firefox-bin`. However, if I type the `ext+container:...` in the URL bar, I have no issues. 

I've tried a few versions of open-url-in-container (both v1 and v2) as well as different versions of Firefox. It looks like this could be a known issue with FF (https://bugzilla.mozilla.org/show_bug.cgi?id=453455), but I was wondering if you've had this issue and might know how to get around it. 

Let me know if you need any other info from me. 

Also just wanted to say thanks for building this out!! If I can get this piece working, I'll have an automation that will save me a few hours a month. 

Thanks,
Spencer Smith

![Screen Shot 2021-05-05 at 2 21 48 PM](https://user-images.githubusercontent.com/7604317/117197275-3bd9a980-adad-11eb-83b4-681a58ae77c8.png)

**Comment by Maryse47** [comment]
Dupe of https://github.com/honsiorovskyi/open-url-in-container/issues/97 ?

**Comment by spencersmith** [comment]
Yep, 100%. Sorry. Should've checked closed issues.
